import { Router } from 'express';
import { requiereAutenticacion } from '../autenticacion/middleware.js';
import { requiereCampos, requiereMembresia } from '../autorizacion/membresia.js';
import { crearEstablecimiento, listarEstablecimientos, obtenerEstablecimiento, actualizarEstablecimiento, eliminarEstablecimiento } from '../controllers/establecimiento.js';
import { expulsarMiembro, generarInvitacion, modificarMiembro, obtenerEquipo, transferir, unirse } from '../controllers/equipo.js';
import { asyncHandler } from '../http/async-handler.js';
import { lotesRouter } from './lotes.js';
import { historialRouter } from './historial.js';
import { climaRouter } from './clima.js';
import { sateliteRouter } from './satelite.js';
import { iaRouter } from './ia.js';
import { simulacionRouter } from './simulacion.js';
import { notificacionesRouter } from './notificaciones.js';

export const establecimientosRouter = Router();
establecimientosRouter.use(requiereAutenticacion);
establecimientosRouter.get('/', asyncHandler(listarEstablecimientos));
establecimientosRouter.post('/', asyncHandler(crearEstablecimiento));
establecimientosRouter.post('/unirse', asyncHandler(unirse));
establecimientosRouter.use('/:establecimientoId', requiereMembresia);
establecimientosRouter.get('/:establecimientoId', asyncHandler(obtenerEstablecimiento));
establecimientosRouter.patch('/:establecimientoId', requiereCampos({ nombre: 'renombrar_establecimiento', polygon: 'editar_limite_establecimiento' }), asyncHandler(actualizarEstablecimiento));
establecimientosRouter.delete('/:establecimientoId', asyncHandler(eliminarEstablecimiento));
establecimientosRouter.get('/:establecimientoId/equipo', asyncHandler(obtenerEquipo));
establecimientosRouter.patch('/:establecimientoId/equipo/:userId', asyncHandler(modificarMiembro));
establecimientosRouter.delete('/:establecimientoId/equipo/:userId', asyncHandler(expulsarMiembro));
establecimientosRouter.post('/:establecimientoId/invitaciones', asyncHandler(generarInvitacion));
establecimientosRouter.post('/:establecimientoId/transferir-principal', asyncHandler(transferir));
establecimientosRouter.use('/:establecimientoId/lotes', climaRouter, sateliteRouter, simulacionRouter, lotesRouter, historialRouter);
establecimientosRouter.use('/:establecimientoId/ia', iaRouter);
establecimientosRouter.use('/:establecimientoId/notificaciones', notificacionesRouter);
